/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator.tables;


import com.iqexception.fxhelper.dal.generator.Fx;
import com.iqexception.fxhelper.dal.generator.Indexes;
import com.iqexception.fxhelper.dal.generator.Keys;
import com.iqexception.fxhelper.dal.generator.tables.records.FxMessageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxMessage extends TableImpl<FxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_message</code>
     */
    public static final FxMessage FX_MESSAGE = new FxMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxMessageRecord> getRecordType() {
        return FxMessageRecord.class;
    }

    /**
     * The column <code>fx.fx_message.ID</code>.
     */
    public final TableField<FxMessageRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_message.MSG_TYPE</code>.
     */
    public final TableField<FxMessageRecord, Integer> MSG_TYPE = createField(DSL.name("MSG_TYPE"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_message.MSG_BODY</code>.
     */
    public final TableField<FxMessageRecord, String> MSG_BODY = createField(DSL.name("MSG_BODY"), SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>fx.fx_message.CHANNEL</code>.
     */
    public final TableField<FxMessageRecord, Integer> CHANNEL = createField(DSL.name("CHANNEL"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_message.USER_ID</code>.
     */
    public final TableField<FxMessageRecord, Long> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>fx.fx_message.SHOP_ID</code>.
     */
    public final TableField<FxMessageRecord, Long> SHOP_ID = createField(DSL.name("SHOP_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>fx.fx_message.STATUS</code>.
     */
    public final TableField<FxMessageRecord, Integer> STATUS = createField(DSL.name("STATUS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_message.FAIL_MSG</code>.
     */
    public final TableField<FxMessageRecord, String> FAIL_MSG = createField(DSL.name("FAIL_MSG"), SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>fx.fx_message.CREATED_AT</code>.
     */
    public final TableField<FxMessageRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_message.UPDATED_AT</code>.
     */
    public final TableField<FxMessageRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxMessage(Name alias, Table<FxMessageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxMessage(Name alias, Table<FxMessageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_message</code> table reference
     */
    public FxMessage(String alias) {
        this(DSL.name(alias), FX_MESSAGE);
    }

    /**
     * Create an aliased <code>fx.fx_message</code> table reference
     */
    public FxMessage(Name alias) {
        this(alias, FX_MESSAGE);
    }

    /**
     * Create a <code>fx.fx_message</code> table reference
     */
    public FxMessage() {
        this(DSL.name("fx_message"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_MESSAGE_IDX_CREATED_AT, Indexes.FX_MESSAGE_IDX_SHOP_ID, Indexes.FX_MESSAGE_IDX_UPDATED_AT, Indexes.FX_MESSAGE_IDX_USER_ID);
    }

    @Override
    public Identity<FxMessageRecord, Long> getIdentity() {
        return (Identity<FxMessageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxMessageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    public FxMessage as(String alias) {
        return new FxMessage(DSL.name(alias), this);
    }

    @Override
    public FxMessage as(Name alias) {
        return new FxMessage(alias, this);
    }

    @Override
    public FxMessage as(Table<?> alias) {
        return new FxMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxMessage rename(String name) {
        return new FxMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxMessage rename(Name name) {
        return new FxMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxMessage rename(Table<?> name) {
        return new FxMessage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxMessage where(Condition condition) {
        return new FxMessage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxMessage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxMessage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxMessage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxMessage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxMessage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxMessage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxMessage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxMessage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxMessage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
