/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator.tables.daos;


import com.iqexception.fxhelper.dal.generator.tables.FxMessage;
import com.iqexception.fxhelper.dal.generator.tables.records.FxMessageRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxMessageDao extends DAOImpl<FxMessageRecord, com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage, Long> {

    /**
     * Create a new FxMessageDao without any configuration
     */
    public FxMessageDao() {
        super(FxMessage.FX_MESSAGE, com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage.class);
    }

    /**
     * Create a new FxMessageDao with an attached configuration
     */
    @Autowired
    public FxMessageDao(Configuration configuration) {
        super(FxMessage.FX_MESSAGE, com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchById(Long... values) {
        return fetch(FxMessage.FX_MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage fetchOneById(Long value) {
        return fetchOne(FxMessage.FX_MESSAGE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchOptionalById(Long value) {
        return fetchOptional(FxMessage.FX_MESSAGE.ID, value);
    }

    /**
     * Fetch records that have <code>MSG_TYPE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfMsgType(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.MSG_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MSG_TYPE IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByMsgType(Integer... values) {
        return fetch(FxMessage.FX_MESSAGE.MSG_TYPE, values);
    }

    /**
     * Fetch records that have <code>MSG_BODY BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfMsgBody(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.MSG_BODY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MSG_BODY IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByMsgBody(String... values) {
        return fetch(FxMessage.FX_MESSAGE.MSG_BODY, values);
    }

    /**
     * Fetch records that have <code>CHANNEL BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfChannel(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.CHANNEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CHANNEL IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByChannel(Integer... values) {
        return fetch(FxMessage.FX_MESSAGE.CHANNEL, values);
    }

    /**
     * Fetch records that have <code>USER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByUserId(Long... values) {
        return fetch(FxMessage.FX_MESSAGE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>SHOP_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfShopId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.SHOP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SHOP_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByShopId(Long... values) {
        return fetch(FxMessage.FX_MESSAGE.SHOP_ID, values);
    }

    /**
     * Fetch records that have <code>STATUS BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByStatus(Integer... values) {
        return fetch(FxMessage.FX_MESSAGE.STATUS, values);
    }

    /**
     * Fetch records that have <code>FAIL_MSG BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfFailMsg(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.FAIL_MSG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>FAIL_MSG IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByFailMsg(String... values) {
        return fetch(FxMessage.FX_MESSAGE.FAIL_MSG, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxMessage.FX_MESSAGE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxMessage.FX_MESSAGE.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(FxMessage.FX_MESSAGE.UPDATED_AT, values);
    }
}
