/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator;


import com.iqexception.fxhelper.dal.generator.tables.FxAccount;
import com.iqexception.fxhelper.dal.generator.tables.FxMessage;
import com.iqexception.fxhelper.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.dal.generator.tables.FxPayInfo;
import com.iqexception.fxhelper.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.dal.generator.tables.FxShop;
import com.iqexception.fxhelper.dal.generator.tables.FxUser;
import com.iqexception.fxhelper.dal.generator.tables.FxWxMsgSubs;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fx extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx</code>
     */
    public static final Fx FX = new Fx();

    /**
     * The table <code>fx.fx_account</code>.
     */
    public final FxAccount FX_ACCOUNT = FxAccount.FX_ACCOUNT;

    /**
     * The table <code>fx.fx_message</code>.
     */
    public final FxMessage FX_MESSAGE = FxMessage.FX_MESSAGE;

    /**
     * The table <code>fx.fx_order</code>.
     */
    public final FxOrder FX_ORDER = FxOrder.FX_ORDER;

    /**
     * The table <code>fx.fx_pay_info</code>.
     */
    public final FxPayInfo FX_PAY_INFO = FxPayInfo.FX_PAY_INFO;

    /**
     * The table <code>fx.fx_serial_no</code>.
     */
    public final FxSerialNo FX_SERIAL_NO = FxSerialNo.FX_SERIAL_NO;

    /**
     * The table <code>fx.fx_shop</code>.
     */
    public final FxShop FX_SHOP = FxShop.FX_SHOP;

    /**
     * The table <code>fx.fx_user</code>.
     */
    public final FxUser FX_USER = FxUser.FX_USER;

    /**
     * The table <code>fx.fx_wx_msg_subs</code>.
     */
    public final FxWxMsgSubs FX_WX_MSG_SUBS = FxWxMsgSubs.FX_WX_MSG_SUBS;

    /**
     * No further instances allowed
     */
    private Fx() {
        super("fx", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FxAccount.FX_ACCOUNT,
            FxMessage.FX_MESSAGE,
            FxOrder.FX_ORDER,
            FxPayInfo.FX_PAY_INFO,
            FxSerialNo.FX_SERIAL_NO,
            FxShop.FX_SHOP,
            FxUser.FX_USER,
            FxWxMsgSubs.FX_WX_MSG_SUBS
        );
    }
}
