/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator;


import com.iqexception.fxhelper.dal.generator.tables.FxAccount;
import com.iqexception.fxhelper.dal.generator.tables.FxMessage;
import com.iqexception.fxhelper.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.dal.generator.tables.FxPayInfo;
import com.iqexception.fxhelper.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.dal.generator.tables.FxShop;
import com.iqexception.fxhelper.dal.generator.tables.FxUser;
import com.iqexception.fxhelper.dal.generator.tables.FxWxMsgSubs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FX_ACCOUNT_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_account_idx_created_at"), FxAccount.FX_ACCOUNT, new OrderField[] { FxAccount.FX_ACCOUNT.CREATED_AT }, false);
    public static final Index FX_ACCOUNT_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_account_idx_updated_at"), FxAccount.FX_ACCOUNT, new OrderField[] { FxAccount.FX_ACCOUNT.UPDATED_AT }, false);
    public static final Index FX_MESSAGE_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_message_idx_created_at"), FxMessage.FX_MESSAGE, new OrderField[] { FxMessage.FX_MESSAGE.CREATED_AT }, false);
    public static final Index FX_MESSAGE_IDX_SHOP_ID = Internal.createIndex(DSL.name("fx_message_idx_shop_id"), FxMessage.FX_MESSAGE, new OrderField[] { FxMessage.FX_MESSAGE.SHOP_ID }, false);
    public static final Index FX_MESSAGE_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_message_idx_updated_at"), FxMessage.FX_MESSAGE, new OrderField[] { FxMessage.FX_MESSAGE.UPDATED_AT }, false);
    public static final Index FX_MESSAGE_IDX_USER_ID = Internal.createIndex(DSL.name("fx_message_idx_user_id"), FxMessage.FX_MESSAGE, new OrderField[] { FxMessage.FX_MESSAGE.USER_ID }, false);
    public static final Index FX_ORDER_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_order_idx_created_at"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.CREATED_AT }, false);
    public static final Index FX_ORDER_IDX_FX_TIME = Internal.createIndex(DSL.name("fx_order_idx_fx_time"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.FX_TIME }, false);
    public static final Index FX_ORDER_IDX_SHOP_ID = Internal.createIndex(DSL.name("fx_order_idx_shop_id"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.SHOP_ID }, false);
    public static final Index FX_ORDER_IDX_SHOP_ID__26_SERIAL_NO = Internal.createIndex(DSL.name("fx_order_idx_shop_id_&_serial_no"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.SHOP_ID, FxOrder.FX_ORDER.SERIAL_NO }, true);
    public static final Index FX_ORDER_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_order_idx_updated_at"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.UPDATED_AT }, false);
    public static final Index FX_ORDER_IDX_USER_ID = Internal.createIndex(DSL.name("fx_order_idx_user_id"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.USER_ID }, false);
    public static final Index FX_PAY_INFO_IDX_BIZ_ID = Internal.createIndex(DSL.name("fx_pay_info_idx_biz_id"), FxPayInfo.FX_PAY_INFO, new OrderField[] { FxPayInfo.FX_PAY_INFO.BIZ_ID }, false);
    public static final Index FX_PAY_INFO_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_pay_info_idx_created_at"), FxPayInfo.FX_PAY_INFO, new OrderField[] { FxPayInfo.FX_PAY_INFO.CREATED_AT }, false);
    public static final Index FX_PAY_INFO_IDX_FROM_ACCOUNT = Internal.createIndex(DSL.name("fx_pay_info_idx_from_account"), FxPayInfo.FX_PAY_INFO, new OrderField[] { FxPayInfo.FX_PAY_INFO.FROM_ACCOUNT }, false);
    public static final Index FX_PAY_INFO_IDX_TO_ACCOUNT = Internal.createIndex(DSL.name("fx_pay_info_idx_to_account"), FxPayInfo.FX_PAY_INFO, new OrderField[] { FxPayInfo.FX_PAY_INFO.TO_ACCOUNT }, false);
    public static final Index FX_PAY_INFO_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_pay_info_idx_updated_at"), FxPayInfo.FX_PAY_INFO, new OrderField[] { FxPayInfo.FX_PAY_INFO.UPDATED_AT }, false);
    public static final Index FX_SERIAL_IDX_NO_CREATED_AT = Internal.createIndex(DSL.name("fx_serial_idx_no_created_at"), FxSerialNo.FX_SERIAL_NO, new OrderField[] { FxSerialNo.FX_SERIAL_NO.CREATED_AT }, false);
    public static final Index FX_SERIAL_IDX_NO_SHOP_I__26_SERIAL_NO = Internal.createIndex(DSL.name("fx_serial_idx_no_shop_i_&_serial_no"), FxSerialNo.FX_SERIAL_NO, new OrderField[] { FxSerialNo.FX_SERIAL_NO.SHOP_ID, FxSerialNo.FX_SERIAL_NO.SERIAL_NO }, true);
    public static final Index FX_SHOP_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_shop_idx_created_at"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.CREATED_AT }, false);
    public static final Index FX_SHOP_IDX_OWNER_USER_ID = Internal.createIndex(DSL.name("fx_shop_idx_owner_user_id"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.OWNER_USER_ID }, false);
    public static final Index FX_SHOP_IDX_PHONE = Internal.createIndex(DSL.name("fx_shop_idx_phone"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.PHONE }, false);
    public static final Index FX_SHOP_IDX_SHOP_NAME = Internal.createIndex(DSL.name("fx_shop_idx_shop_name"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.SHOP_NAME }, false);
    public static final Index FX_SHOP_IDX_SHOP_NAME__26_ADDRESS = Internal.createIndex(DSL.name("fx_shop_idx_shop_name_&_address"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.SHOP_NAME, FxShop.FX_SHOP.ADDRESS }, true);
    public static final Index FX_SHOP_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_shop_idx_updated_at"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.UPDATED_AT }, false);
    public static final Index FX_USER_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_user_idx_created_at"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.CREATED_AT }, false);
    public static final Index FX_USER_IDX_NICK_NAME = Internal.createIndex(DSL.name("fx_user_idx_nick_name"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.NICK_NAME }, false);
    public static final Index FX_USER_IDX_OPEN_ID = Internal.createIndex(DSL.name("fx_user_idx_open_id"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.OPEN_ID }, false);
    public static final Index FX_USER_IDX_PHONE = Internal.createIndex(DSL.name("fx_user_idx_phone"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.PHONE }, false);
    public static final Index FX_USER_IDX_SESSION_KEY = Internal.createIndex(DSL.name("fx_user_idx_session_key"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.SESSION_KEY }, false);
    public static final Index FX_USER_IDX_UNION_ID = Internal.createIndex(DSL.name("fx_user_idx_union_id"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.UNION_ID }, false);
    public static final Index FX_USER_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_user_idx_updated_at"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.UPDATED_AT }, false);
    public static final Index FX_WX_MSG_SUBS_IDX_OPEN_ID__26_TEMPLATE_ID = Internal.createIndex(DSL.name("fx_wx_msg_subs_idx_open_id_&_template_id"), FxWxMsgSubs.FX_WX_MSG_SUBS, new OrderField[] { FxWxMsgSubs.FX_WX_MSG_SUBS.OPEN_ID, FxWxMsgSubs.FX_WX_MSG_SUBS.TEMPLATE_ID }, true);
}
