/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator;


import com.iqexception.fxhelper.dal.generator.tables.FxAccount;
import com.iqexception.fxhelper.dal.generator.tables.FxMessage;
import com.iqexception.fxhelper.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.dal.generator.tables.FxPayInfo;
import com.iqexception.fxhelper.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.dal.generator.tables.FxShop;
import com.iqexception.fxhelper.dal.generator.tables.FxUser;
import com.iqexception.fxhelper.dal.generator.tables.FxWxMsgSubs;
import com.iqexception.fxhelper.dal.generator.tables.records.FxAccountRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxMessageRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxOrderRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxPayInfoRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxSerialNoRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxShopRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxUserRecord;
import com.iqexception.fxhelper.dal.generator.tables.records.FxWxMsgSubsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxAccountRecord> CONSTRAINT_1 = Internal.createUniqueKey(FxAccount.FX_ACCOUNT, DSL.name("CONSTRAINT_1"), new TableField[] { FxAccount.FX_ACCOUNT.ACCOUNT_ID }, true);
    public static final UniqueKey<FxAccountRecord> CONSTRAINT_1B = Internal.createUniqueKey(FxAccount.FX_ACCOUNT, DSL.name("CONSTRAINT_1B"), new TableField[] { FxAccount.FX_ACCOUNT.USER_ID }, true);
    public static final UniqueKey<FxMessageRecord> CONSTRAINT_9 = Internal.createUniqueKey(FxMessage.FX_MESSAGE, DSL.name("CONSTRAINT_9"), new TableField[] { FxMessage.FX_MESSAGE.ID }, true);
    public static final UniqueKey<FxOrderRecord> CONSTRAINT_D = Internal.createUniqueKey(FxOrder.FX_ORDER, DSL.name("CONSTRAINT_D"), new TableField[] { FxOrder.FX_ORDER.ID }, true);
    public static final UniqueKey<FxPayInfoRecord> CONSTRAINT_2 = Internal.createUniqueKey(FxPayInfo.FX_PAY_INFO, DSL.name("CONSTRAINT_2"), new TableField[] { FxPayInfo.FX_PAY_INFO.ID }, true);
    public static final UniqueKey<FxPayInfoRecord> CONSTRAINT_2C = Internal.createUniqueKey(FxPayInfo.FX_PAY_INFO, DSL.name("CONSTRAINT_2C"), new TableField[] { FxPayInfo.FX_PAY_INFO.BIZ_ID }, true);
    public static final UniqueKey<FxSerialNoRecord> CONSTRAINT_6 = Internal.createUniqueKey(FxSerialNo.FX_SERIAL_NO, DSL.name("CONSTRAINT_6"), new TableField[] { FxSerialNo.FX_SERIAL_NO.ID }, true);
    public static final UniqueKey<FxShopRecord> CONSTRAINT_E5F = Internal.createUniqueKey(FxShop.FX_SHOP, DSL.name("CONSTRAINT_E5F"), new TableField[] { FxShop.FX_SHOP.SHOP_ID }, true);
    public static final UniqueKey<FxUserRecord> CONSTRAINT_E = Internal.createUniqueKey(FxUser.FX_USER, DSL.name("CONSTRAINT_E"), new TableField[] { FxUser.FX_USER.USER_ID }, true);
    public static final UniqueKey<FxUserRecord> CONSTRAINT_E5 = Internal.createUniqueKey(FxUser.FX_USER, DSL.name("CONSTRAINT_E5"), new TableField[] { FxUser.FX_USER.OPEN_ID }, true);
    public static final UniqueKey<FxWxMsgSubsRecord> CONSTRAINT_18 = Internal.createUniqueKey(FxWxMsgSubs.FX_WX_MSG_SUBS, DSL.name("CONSTRAINT_18"), new TableField[] { FxWxMsgSubs.FX_WX_MSG_SUBS.ID }, true);
}
