/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator;


import com.iqexception.fxhelper.dal.generator.tables.FxAccount;
import com.iqexception.fxhelper.dal.generator.tables.FxMessage;
import com.iqexception.fxhelper.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.dal.generator.tables.FxPayInfo;
import com.iqexception.fxhelper.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.dal.generator.tables.FxShop;
import com.iqexception.fxhelper.dal.generator.tables.FxUser;
import com.iqexception.fxhelper.dal.generator.tables.FxWxMsgSubs;


/**
 * Convenience access to all tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>fx.fx_account</code>.
     */
    public static final FxAccount FX_ACCOUNT = FxAccount.FX_ACCOUNT;

    /**
     * The table <code>fx.fx_message</code>.
     */
    public static final FxMessage FX_MESSAGE = FxMessage.FX_MESSAGE;

    /**
     * The table <code>fx.fx_order</code>.
     */
    public static final FxOrder FX_ORDER = FxOrder.FX_ORDER;

    /**
     * The table <code>fx.fx_pay_info</code>.
     */
    public static final FxPayInfo FX_PAY_INFO = FxPayInfo.FX_PAY_INFO;

    /**
     * The table <code>fx.fx_serial_no</code>.
     */
    public static final FxSerialNo FX_SERIAL_NO = FxSerialNo.FX_SERIAL_NO;

    /**
     * The table <code>fx.fx_shop</code>.
     */
    public static final FxShop FX_SHOP = FxShop.FX_SHOP;

    /**
     * The table <code>fx.fx_user</code>.
     */
    public static final FxUser FX_USER = FxUser.FX_USER;

    /**
     * The table <code>fx.fx_wx_msg_subs</code>.
     */
    public static final FxWxMsgSubs FX_WX_MSG_SUBS = FxWxMsgSubs.FX_WX_MSG_SUBS;
}
