/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator.tables.records;


import com.iqexception.fxhelper.dal.generator.tables.FxMessage;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxMessageRecord extends UpdatableRecordImpl<FxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_message.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_message.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_message.MSG_TYPE</code>.
     */
    public void setMsgType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_message.MSG_TYPE</code>.
     */
    public Integer getMsgType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fx.fx_message.MSG_BODY</code>.
     */
    public void setMsgBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_message.MSG_BODY</code>.
     */
    public String getMsgBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_message.CHANNEL</code>.
     */
    public void setChannel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_message.CHANNEL</code>.
     */
    public Integer getChannel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fx.fx_message.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_message.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>fx.fx_message.SHOP_ID</code>.
     */
    public void setShopId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_message.SHOP_ID</code>.
     */
    public Long getShopId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fx.fx_message.STATUS</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fx.fx_message.STATUS</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fx.fx_message.FAIL_MSG</code>.
     */
    public void setFailMsg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fx.fx_message.FAIL_MSG</code>.
     */
    public String getFailMsg() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fx.fx_message.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>fx.fx_message.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>fx.fx_message.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fx.fx_message.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxMessageRecord
     */
    public FxMessageRecord() {
        super(FxMessage.FX_MESSAGE);
    }

    /**
     * Create a detached, initialised FxMessageRecord
     */
    public FxMessageRecord(Long id, Integer msgType, String msgBody, Integer channel, Long userId, Long shopId, Integer status, String failMsg, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxMessage.FX_MESSAGE);

        setId(id);
        setMsgType(msgType);
        setMsgBody(msgBody);
        setChannel(channel);
        setUserId(userId);
        setShopId(shopId);
        setStatus(status);
        setFailMsg(failMsg);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxMessageRecord
     */
    public FxMessageRecord(com.iqexception.fxhelper.dal.generator.tables.pojos.FxMessage value) {
        super(FxMessage.FX_MESSAGE);

        if (value != null) {
            setId(value.getId());
            setMsgType(value.getMsgType());
            setMsgBody(value.getMsgBody());
            setChannel(value.getChannel());
            setUserId(value.getUserId());
            setShopId(value.getShopId());
            setStatus(value.getStatus());
            setFailMsg(value.getFailMsg());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
