/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.dal.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxMessage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer msgType;
    private String msgBody;
    private Integer channel;
    private Long userId;
    private Long shopId;
    private Integer status;
    private String failMsg;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FxMessage() {}

    public FxMessage(FxMessage value) {
        this.id = value.id;
        this.msgType = value.msgType;
        this.msgBody = value.msgBody;
        this.channel = value.channel;
        this.userId = value.userId;
        this.shopId = value.shopId;
        this.status = value.status;
        this.failMsg = value.failMsg;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FxMessage(
        Long id,
        Integer msgType,
        String msgBody,
        Integer channel,
        Long userId,
        Long shopId,
        Integer status,
        String failMsg,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.msgType = msgType;
        this.msgBody = msgBody;
        this.channel = channel;
        this.userId = userId;
        this.shopId = shopId;
        this.status = status;
        this.failMsg = failMsg;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>fx.fx_message.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>fx.fx_message.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>fx.fx_message.MSG_TYPE</code>.
     */
    public Integer getMsgType() {
        return this.msgType;
    }

    /**
     * Setter for <code>fx.fx_message.MSG_TYPE</code>.
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * Getter for <code>fx.fx_message.MSG_BODY</code>.
     */
    public String getMsgBody() {
        return this.msgBody;
    }

    /**
     * Setter for <code>fx.fx_message.MSG_BODY</code>.
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }

    /**
     * Getter for <code>fx.fx_message.CHANNEL</code>.
     */
    public Integer getChannel() {
        return this.channel;
    }

    /**
     * Setter for <code>fx.fx_message.CHANNEL</code>.
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * Getter for <code>fx.fx_message.USER_ID</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fx.fx_message.USER_ID</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fx.fx_message.SHOP_ID</code>.
     */
    public Long getShopId() {
        return this.shopId;
    }

    /**
     * Setter for <code>fx.fx_message.SHOP_ID</code>.
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * Getter for <code>fx.fx_message.STATUS</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>fx.fx_message.STATUS</code>.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>fx.fx_message.FAIL_MSG</code>.
     */
    public String getFailMsg() {
        return this.failMsg;
    }

    /**
     * Setter for <code>fx.fx_message.FAIL_MSG</code>.
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg;
    }

    /**
     * Getter for <code>fx.fx_message.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>fx.fx_message.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>fx.fx_message.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>fx.fx_message.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FxMessage other = (FxMessage) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.msgType == null) {
            if (other.msgType != null)
                return false;
        }
        else if (!this.msgType.equals(other.msgType))
            return false;
        if (this.msgBody == null) {
            if (other.msgBody != null)
                return false;
        }
        else if (!this.msgBody.equals(other.msgBody))
            return false;
        if (this.channel == null) {
            if (other.channel != null)
                return false;
        }
        else if (!this.channel.equals(other.channel))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!this.shopId.equals(other.shopId))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.failMsg == null) {
            if (other.failMsg != null)
                return false;
        }
        else if (!this.failMsg.equals(other.failMsg))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.msgType == null) ? 0 : this.msgType.hashCode());
        result = prime * result + ((this.msgBody == null) ? 0 : this.msgBody.hashCode());
        result = prime * result + ((this.channel == null) ? 0 : this.channel.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.failMsg == null) ? 0 : this.failMsg.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FxMessage (");

        sb.append(id);
        sb.append(", ").append(msgType);
        sb.append(", ").append(msgBody);
        sb.append(", ").append(channel);
        sb.append(", ").append(userId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(status);
        sb.append(", ").append(failMsg);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
